services:
  - type: web
    name: EnFxzz
    runtime: node
    buildCommand: corepack enable && pnpm install --prod --frozen-lockfile
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
